import test from 'node:test';
import assert from 'node:assert/strict';
import {expression,autoVariation,tableWarnings} from '../src/math.js';
import {buildScene,initialTable,initialTree} from '../src/project.js';
import {toTypst,toSVG,parseTree} from '../src/drawing.js';
const auto=s=>autoVariation(expression(s));
const options={xmin:-4,xmax:4,ymin:-4,ymax:6,color:'#2755df',title:'',showGrid:true,showPoints:true};
test('cubic stationary points, values, signs and infinite limits',()=>{const t=auto('x^3-3*x+1');assert.deepEqual(t.points.map(p=>p.x),['−∞','-1','1','+∞']);assert.deepEqual(t.points.map(p=>p.y),['−∞','3','-1','+∞']);assert.deepEqual(t.signs,['+','−','+']);});
test('quartic and repeated derivative root',()=>{assert.deepEqual(auto('x^4-2*x^2').signs,['−','+','−','+']);assert.deepEqual(auto('x^3').signs,['+','+']);assert.equal(auto('x^3').points[1].x,'0');});
test('constant and linear',()=>{assert.deepEqual(auto('5').signs,['0']);assert.equal(auto('5').points[0].y,'5');assert.deepEqual(auto('-2*x+1').signs,['−']);});
test('small nonzero coefficients are preserved',()=>{assert.equal(auto('0.000000001*x').kind,'Đa thức bậc 1');assert.deepEqual(auto('0.000000001*x').signs,['+']);});
test('rational pole has separate one-sided limits',()=>{const t=auto('(2*x+1)/(x-1)');assert.deepEqual(t.signs,['−','−']);assert.equal(t.points[1].y,'−∞');assert.equal(t.points[1].right,'+∞');assert.deepEqual(t.poles,[1]);});
test('removable discontinuity does not become vertical asymptote',()=>{const t=auto('(2*x-2)/(x-1)');assert.deepEqual(t.poles,[]);assert.deepEqual(t.holes,[{x:1,y:2}]);assert.equal(t.points[1].mark,'||');});
test('known domains and unsupported auto cases',()=>{assert.equal(auto('ln(x)').domain,'(0; +∞)');assert.equal(auto('sqrt(x)').domain,'[0; +∞)');assert.equal(auto('sin(x)'),null);assert.equal(auto('(x^2-1)/(x-1)'),null);});
test('reject assignments, properties, complex constructs, arbitrary symbols',()=>{for(const s of ['x=3','a+1','import("x")','[1,2]','x.foo','x!','f(x)=x'])assert.throws(()=>expression(s),undefined,s);});
test('basic safe expressions evaluate',()=>{assert.equal(expression('y = 2x² − 3').evaluate(2),5);assert.equal(expression('ln(x)').evaluate(1),0);assert.ok(Number.isNaN(expression('sqrt(x)').evaluate(-1)));});
test('manual table detects inconsistent monotonicity and x ordering',()=>{const t=initialTable();t.signs[0]='−';assert.ok(tableWarnings(t).length);t.points[2].x='-2';assert.ok(tableWarnings(t).some(s=>s.includes('tăng')));});
test('tree hierarchy supports multiple levels and rejects broken indentation',()=>{assert.equal(parseTree(initialTree).nodes.length,7);assert.throws(()=>parseTree('A\n   B'));assert.throws(()=>parseTree('A\nB'));});
test('render every mode, escape user labels in SVG and Typst',()=>{for(const mode of ['graph','variation','tree','illustration']){const s=buildScene({version:1,mode,formula:'x^3-3*x+1',table:initialTable(),tree:initialTree,options});assert.ok(s.items.length>0);assert.ok(toTypst(s).includes('#set page'));assert.ok(toSVG(s).startsWith('<svg'));}const s=buildScene({version:1,mode:'variation',table:initialTable(),options:{...options,title:'<script>"#read("secret")'}});assert.ok(!toSVG(s).includes('<script>'));assert.ok(toTypst(s).includes('\\"#read('));});
test('reject invalid ranges and colors',()=>{for(const o of [{xmin:4,xmax:1},{ymin:0,ymax:0},{color:'red); #read("x")'}])assert.throws(()=>buildScene({version:1,mode:'graph',formula:'x',options:{...options,...o}}));});
test('graph does not bridge the pole',()=>{const s=buildScene({version:1,mode:'graph',formula:'1/x',options});const paths=s.items.filter(p=>p.type==='polyline');const zero=s.plot.left+s.plot.width/2;assert.ok(paths.length>=2);assert.ok(paths.every(p=>p.points.every(([x])=>x<=zero)||p.points.every(([x])=>x>=zero)));});
test('sqrt is defined at zero although its derivative is not',()=>{const t=auto('sqrt(x)');assert.equal(t.points[0].mark,'||');assert.equal(t.points[0].split,false);assert.equal(t.points[0].y,'0');});
test('wide manual tables reserve room for arrows',()=>{const table={points:Array.from({length:10},(_,i)=>({x:String(i),y:String(i),mark:'0'})),signs:Array(9).fill('+')};const s=buildScene({version:1,mode:'variation',table,options});assert.ok(s.width>900);assert.ok(toTypst(s).length>1000);});
