import { simplify } from './viewport.js';
import { mathLabel, typstLabel } from './math-typeset.js';
import { variationTypst } from './variation-typst.js';
import { fmt, numericLabel, tableWarnings, validateTable, rightValue } from './math.js';

const ink='#24334b',muted='#778397',grid='#e9edf4';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=n=>Number(n.toFixed(3));
const pretty=s=>String(s).replace(/\^([0-9]+)/g,(_,n)=>[...n].map(c=>'⁰¹²³⁴⁵⁶⁷⁸⁹'[+c]).join('')).replace(/\*/g,'·').replace(/-/g,'−');
export function scene(width=900,height=540){return {width,height,items:[]};}
function line(s,x1,y1,x2,y2,color=ink,width=1.3,dash=false){s.items.push({type:'line',x1,y1,x2,y2,color,width,dash});}
function text(s,x,y,label,size=18,color=ink,anchor='middle'){s.items.push({type:'text',x,y,label:String(label),size,color,anchor});}
function rect(s,x,y,w,h,fill,stroke=fill){s.items.push({type:'rect',x,y,w,h,fill,stroke});}
function dot(s,x,y,r=4,color='#2755df',open=false){s.items.push({type:'circle',x,y,r,color,open});}
function arrow(s,x1,y1,x2,y2,color=ink,width=1.8){line(s,x1,y1,x2,y2,color,width);const a=Math.atan2(y2-y1,x2-x1),l=8;line(s,x2,y2,x2-l*Math.cos(a-.45),y2-l*Math.sin(a-.45),color,width);line(s,x2,y2,x2-l*Math.cos(a+.45),y2-l*Math.sin(a+.45),color,width);}
function polyline(s,points,color,width=2.3){if(points.length>1)s.items.push({type:'polyline',points:simplify(points),color,width});}
export function toSVG(s){
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${s.width}" height="${s.height}" viewBox="0 0 ${s.width} ${s.height}" role="img" aria-label="Hình vẽ toán học"><rect width="100%" height="100%" fill="white"/>${s.items.map(p=>{
    if(p.type==='line')return `<line x1="${f(p.x1)}" y1="${f(p.y1)}" x2="${f(p.x2)}" y2="${f(p.y2)}" stroke="${p.color}" stroke-width="${p.width}" ${p.dash?'stroke-dasharray="5 5"':''}/>`;
    if(p.type==='text'&&mathLabel(p.label)){const m=mathLabel(p.label),w=m.width*p.size,h=m.height*p.size,x=p.anchor==='middle'?p.x-w/2:p.anchor==='end'?p.x-w:p.x;return `<svg x="${f(x)}" y="${f(p.y-h/2)}" width="${w}" height="${h}" viewBox="${m.viewBox.join(' ')}" color="${p.color}" fill="${p.color}">${m.body}</svg>`;}
    if(p.type==='text')return `<text x="${f(p.x)}" y="${f(p.y)}" font-family="Georgia, 'Times New Roman', serif" font-size="${p.size}" fill="${p.color}" text-anchor="${p.anchor}" dominant-baseline="middle">${esc(p.label)}</text>`;
    if(p.type==='rect')return `<rect x="${f(p.x)}" y="${f(p.y)}" width="${p.w}" height="${p.h}" rx="7" fill="${p.fill}" stroke="${p.stroke}"/>`;
    if(p.type==='circle')return `<circle cx="${f(p.x)}" cy="${f(p.y)}" r="${p.r}" fill="${p.open?'white':p.color}" stroke="${p.color}" stroke-width="1.7"/>`;
    return `<polyline points="${p.points.map(([x,y])=>`${f(x)},${f(y)}`).join(' ')}" fill="none" stroke="${p.color}" stroke-width="${p.width}" stroke-linejoin="round" stroke-linecap="round"/>`;
  }).join('')}</svg>`;
}
// Native Typst primitives: editable vector source, with no external packages or images.
export function toTypst(s){
  if(s.table)return variationTypst(s.table,s.tableOptions,s.width);
  const q=v=>JSON.stringify(String(v));
  const pos=(x,y,body)=>`#place(top + left, dx: ${f(x)}pt, dy: ${f(y)}pt, ${body})`;
  const stroke=(color,width,dash=false)=>`(paint: rgb("${color}"), thickness: ${width}pt${dash?', dash: "dashed"':''})`;
  const lines=[`// Generated by Đồ Thị Studio. Native, self-contained Typst.`,`#set page(width: ${s.width}pt, height: ${s.height}pt, margin: 0pt, fill: white)`,`#set text(font: ("Libertinus Serif", "DejaVu Serif"), size: 18pt)`,`#show math.equation: set text(font: "New Computer Modern Math")`,`#set par(leading: 0pt)`];
  for(const p of s.items){
    if(p.type==='line') lines.push(pos(0,0,`line(start: (${f(p.x1)}pt, ${f(p.y1)}pt), end: (${f(p.x2)}pt, ${f(p.y2)}pt), stroke: ${stroke(p.color,p.width,p.dash)})`));
    if(p.type==='polyline') lines.push(pos(0,0,`curve(curve.move((${f(p.points[0][0])}pt, ${f(p.points[0][1])}pt)), ${p.points.slice(1).map(([x,y])=>`curve.line((${f(x)}pt, ${f(y)}pt))`).join(', ')}, stroke: ${stroke(p.color,p.width)})`));
    if(p.type==='circle')lines.push(pos(p.x-p.r,p.y-p.r,`circle(radius: ${p.r}pt, fill: ${p.open?'white':`rgb("${p.color}")`}, stroke: ${stroke(p.color,1.7)})`));
    if(p.type==='rect')lines.push(pos(p.x,p.y,`rect(width: ${p.w}pt, height: ${p.h}pt, radius: 7pt, fill: rgb("${p.fill}"), stroke: rgb("${p.stroke}"))`));
    if(p.type==='text'){
      const align=p.anchor==='middle'?'center':p.anchor==='end'?'right':'left';
      const w=Math.max(80,p.label.length*p.size*.8),x=p.anchor==='middle'?p.x-w/2:p.anchor==='end'?p.x-w:p.x;
      lines.push(pos(x,p.y-p.size*.65,`box(width: ${f(w)}pt, height: ${p.size*1.5}pt, align(${align}, text(size: ${p.size}pt, fill: rgb("${p.color}"), ${typstLabel(p.label)})))`));
    }
  }
  return lines.join('\n')+'\n';
}
export function graph(ex,table,options={},extra=[]){
  const {xmin=-5,xmax=5,ymin=-5,ymax=5,color='#2755df',showGrid=true,showPoints=true,title=''}=options;
  if(![xmin,xmax,ymin,ymax].every(Number.isFinite)||xmax<=xmin||ymax<=ymin||xmax-xmin<1e-6||ymax-ymin<1e-6||Math.max(...[xmin,xmax,ymin,ymax].map(Math.abs))>1e6)throw new Error('Khoảng trục không hợp lệ: min < max, độ rộng ≥ 10⁻⁶, giá trị trong ±10⁶.');
  const sx=xmax-xmin,sy=ymax-ymin,unit=600/Math.max(sx,sy),L=75,T=65,R=L+sx*unit,B=T+sy*unit;
  const legend=extra.length?35*(extra.length+1):0;
  const s=scene(Math.max(360,R+65),B+60+legend);s.plot={left:L,top:T,width:R-L,height:B-T,unit};
  const X=x=>L+(x-xmin)/(xmax-xmin)*(R-L),Y=y=>B-(y-ymin)/(ymax-ymin)*(B-T);
  const ox=Math.min(R,Math.max(L,X(0))),oy=Math.min(B,Math.max(T,Y(0)));
  const step=range=>{const p=10**Math.floor(Math.log10(range/9)),n=range/9/p;return(n>5?10:n>2?5:n>1?2:1)*p;};
  const dx=step(Math.max(sx,sy)),dy=dx;
  for(let x=Math.ceil(xmin/dx)*dx;x<=xmax+dx*1e-8;x+=dx){if(showGrid)line(s,X(x),T,X(x),B,grid,.8);if(Math.abs(x)>dx*1e-8){line(s,X(x),oy-3,X(x),oy+3,muted,1);text(s,X(x),Math.min(B+20,oy+20),fmt(x),13,muted);}}
  for(let y=Math.ceil(ymin/dy)*dy;y<=ymax+dy*1e-8;y+=dy){if(showGrid)line(s,L,Y(y),R,Y(y),grid,.8);if(Math.abs(y)>dy*1e-8){line(s,ox-3,Y(y),ox+3,Y(y),muted,1);text(s,Math.max(30,ox-14),Y(y),fmt(y),13,muted,'end');}}
  arrow(s,L,oy,R+12,oy,ink,1.2);arrow(s,ox,B,ox,T-12,ink,1.2);
  text(s,R+23,oy,'x',18);text(s,ox+18,T+12,'y',18);if(xmin<=0&&xmax>=0&&ymin<=0&&ymax>=0)text(s,ox-12,oy+18,'O',13,muted);
  text(s,s.width/2,25,title||(extra.length?'So sánh các hàm số':`y = ${ex.source}`),20);
  const curves=[{ex,table,color},...extra];
  for(const [index,curve] of curves.entries()){
  const {ex,table,color}=curve;
  if(extra.length){line(s,75,B+42+index*35,103,B+42+index*35,color,2.5);text(s,115,B+42+index*35,`y = ${ex.source}`,18,color,'start');}
  for(const p of table?.poles||[])if(p>xmin&&p<xmax)line(s,X(p),T,X(p),B,'#d19055',1.3,true);
  let points=[]; const flush=()=>{polyline(s,points,color,2.5);points=[];};
  const count=1500;
  for(let i=0;i<=count;i++){
    const x=xmin+(xmax-xmin)*i/count,y=ex.evaluate(x),py=Y(y);
    if(!Number.isFinite(y)||py<T||py>B){flush();continue;}
    if(points.length){const prev=points.at(-1),lastX=x-(xmax-xmin)/count,mid=Y(ex.evaluate((x+lastX)/2));if(Math.abs(py-prev[1])>100||!Number.isFinite(mid)||Math.abs(mid-(py+prev[1])/2)>12)flush();}
    points.push([X(x),py]);
  }flush();
  if(showPoints)for(const p of table?.points||[]){const x=numericLabel(p.x),y=ex.evaluate(x);if(p.mark==='0'&&x>xmin&&x<xmax&&y>ymin&&y<ymax){line(s,X(x),oy,X(x),Y(y),'#a6b7e9',1,true);dot(s,X(x),Y(y),4,color);text(s,X(x)+10,Y(y)-16,`(${fmt(x)}; ${fmt(y)})`,14,color,'start');}}
  for(const p of table?.holes||[])if(p.x>xmin&&p.x<xmax&&p.y>ymin&&p.y<ymax)dot(s,X(p.x),Y(p.y),5,color,true);
  }
  return s;
}
export function variation(t,{color='#2755df',title='Bảng biến thiên'}={}){
  validateTable(t);const n=t.points.length,width=Math.max(900,220+(n-1)*180),s=scene(width,370),left=55,sep=120,right=width-50,top=75,bottom=325;
  s.table=structuredClone(t);s.tableOptions={color,title};s.hits=[];
  text(s,width/2,30,title||'Bảng biến thiên',21);const X=i=>165+i*((width-260)/(n-1));
  line(s,left,125,right,125);line(s,left,178,right,178);line(s,sep,top,sep,bottom);
  text(s,86,100,'x',22);text(s,86,152,'y′',22);text(s,86,248,'y',22);
  const values=t.points.flatMap(p=>[numericLabel(p.y),numericLabel(rightValue(p))]).filter(Number.isFinite),lo=Math.min(...values),hi=Math.max(...values);
  const Y=v=>{const num=numericLabel(v);return num===Infinity?204:num===-Infinity?303:Number.isFinite(num)?(hi===lo?253:284-(num-lo)/(hi-lo)*62):253;};
  t.points.forEach((p,i)=>{
    const x=X(i);text(s,x,100,p.x,22);
    s.hits.push({x:x-36,y:79,w:72,h:42,index:i,key:'x',label:`Mốc ${i+1}: x`},{x:x-22,y:130,w:44,h:44,index:i,key:'mark',label:`Mốc ${i+1}: y′`});
    const split=p.split??(p.mark==='||');
    if(p.mark==='||'){line(s,x-3,130,x-3,177);line(s,x+3,130,x+3,177);}else text(s,x,152,p.mark,20);
    if(split){line(s,x-3,178,x-3,bottom);line(s,x+3,178,x+3,bottom);if(i>0)text(s,x-13,Y(p.y),p.y,17,ink,'end');if(i<n-1)text(s,x+13,Y(p.right??p.y),p.right??p.y,17,ink,'start');}
    else text(s,x,Y(p.y),p.y,22);
    if(split){if(i>0)s.hits.push({x:x-88,y:Y(p.y)-22,w:76,h:44,index:i,key:'y',label:`Mốc ${i+1}: giới hạn trái`});if(i<n-1)s.hits.push({x:x+12,y:Y(p.right??p.y)-22,w:76,h:44,index:i,key:'right',label:`Mốc ${i+1}: giới hạn phải`});}
    else s.hits.push({x:x-36,y:Y(p.y)-22,w:72,h:44,index:i,key:'y',label:`Mốc ${i+1}: y`});
    s.hits.push({x:x-12,y:180,w:24,h:28,index:i,key:'split',label:`Mốc ${i+1}: ngắt dòng y`});
  });
  t.signs.forEach((sign,i)=>{
    const a=t.points[i],b=t.points[i+1],x1=X(i)+((a.split??(a.mark==='||'))?70:38),x2=X(i+1)-((b.split??(b.mark==='||'))?70:38);
    text(s,(X(i)+X(i+1))/2,152,sign,23,color);
    s.hits.push({x:(X(i)+X(i+1))/2-25,y:130,w:50,h:44,index:i,key:'sign',label:`Khoảng ${i+1}: dấu y′`});
    if(sign==='||'){text(s,(x1+x2)/2,250,'Không xác định',11,muted);return;}
    let y1=Y(rightValue(a)),y2=Y(b.y);
    if(!Number.isFinite(numericLabel(a.right??a.y))&&!['+∞','−∞','-∞'].includes(a.right??a.y))y1=sign==='+'?292:210;
    if(!Number.isFinite(numericLabel(b.y))&&!['+∞','−∞','-∞'].includes(b.y))y2=sign==='+'?210:292;
    if(sign==='0')y2=y1;
    arrow(s,x1,y1,x2,y2,color,1.7);
  });
  return s;
}
export function illustration(t,opts){
  validateTable(t);const warnings=tableWarnings(t);if(warnings.length)throw new Error(warnings.join(' '));
  const {xmin,xmax,ymin,ymax}=opts,xs=t.points.map(p=>numericLabel(p.x));
  const leftValues=t.points.map(p=>numericLabel(p.y)),rightValues=t.points.map(p=>numericLabel(rightValue(p)));
  if([...leftValues,...rightValues].some(Number.isNaN))throw new Error('Phác họa cần y là số, biểu thức số hoặc ±∞. Nhãn tự do chỉ dùng trong bảng.');
  const ex={source:'Đường cong minh họa từ bảng — không xác định duy nhất',evaluate(x){
    const i=xs.findIndex((v,j)=>j<xs.length-1&&x>v&&x<xs[j+1]);if(i<0||t.signs[i]==='||')return NaN;
    const a=Number.isFinite(xs[i])?xs[i]:xmin,b=Number.isFinite(xs[i+1])?xs[i+1]:xmax;
    const rawA=rightValues[i],rawB=leftValues[i+1];
    if(Number.isNaN(rawA)||Number.isNaN(rawB))return NaN;
    const av=Number.isFinite(rawA)?rawA:rawA>0?ymax:ymin,bv=Number.isFinite(rawB)?rawB:rawB>0?ymax:ymin;
    const u=Math.max(0,Math.min(1,(x-a)/(b-a)));return av+(bv-av)*(3*u*u-2*u*u*u);
  }};
  return graph(ex,null,{...opts,title:'Phác họa minh họa từ bảng biến thiên'});
}
export function parseTree(source){
  const lines=source.split('\n').filter(x=>x.trim());if(!lines.length||lines.length>31)throw new Error('Sơ đồ cần 1–31 nút.');
  const nodes=[],stack=[];
  lines.forEach((raw,i)=>{
    if(raw.includes('\t'))throw new Error('Dùng 2 dấu cách cho mỗi cấp, không dùng Tab.');
    const spaces=raw.length-raw.trimStart().length,depth=spaces/2;
    if(!Number.isInteger(depth)||depth>5||(i===0&&depth!==0)||(i>0&&depth===0)||depth>stack.length)throw new Error(`Dòng ${i+1}: mỗi cấp thụt 2 dấu cách, chỉ có một nút gốc.`);
    const [label,...rest]=raw.trim().split('|'),edge=rest.join('|').trim();if(!label.trim()||label.length>28||edge.length>20)throw new Error('Tên nút tối đa 28 ký tự, nhãn nhánh tối đa 20 ký tự.');
    const node={label:label.trim(),edge,depth,children:[]};if(depth)stack[depth-1].children.push(node);nodes.push(node);stack[depth]=node;stack.length=depth+1;
  });return {root:nodes[0],nodes};
}
export function tree(source,{color='#2755df',title='Sơ đồ cây'}={}){
  const {root,nodes}=parseTree(source),leaves=nodes.filter(n=>!n.children.length).length,height=Math.max(430,leaves*64+100),s=scene(900,height),depth=Math.max(1,...nodes.map(n=>n.depth));let k=0;
  const layout=n=>{n.x=90+n.depth*(720/depth);n.y=n.children.length?(n.children.forEach(layout),n.children.reduce((v,c)=>v+c.y,0)/n.children.length):90+(++k-.5)*(height-130)/leaves;};layout(root);
  text(s,450,32,title||'Sơ đồ cây',22);
  nodes.forEach(n=>n.children.forEach(c=>{line(s,n.x+48,n.y,c.x-48,c.y,'#9aaccb',1.4);if(c.edge)text(s,(n.x+c.x)/2,(n.y+c.y)/2-12,c.edge,15,muted);}));
  nodes.forEach(n=>{rect(s,n.x-48,n.y-19,96,38,n===root?color:'#f0f4ff',n===root?color:'#dbe3f3');text(s,n.x,n.y,n.label,Math.min(16,140/n.label.length+6),n===root?'#ffffff':ink);});return s;
}
